/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zzppackage.app;


public class App {
    public static void main(String[] args) {

        System.out.println(MessageUtils.getMessage());
    }
}
